name: shopping
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State management
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  # Dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.3

dev_dependencies:
  lint: ^1.8.2
  injectable_generator: ^1.5.3

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
