name: shopping
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  uuid: ^3.0.6

  # State management
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  # Dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.3

  multiple_result:
    git:
      url: https://github.com/Andree98/result.git
      ref: main

  # Codegen
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  injectable_generator: ^1.5.3
  intl: ^0.17.0
  mocktail: ^0.3.0
  bloc_test: ^9.0.3

dev_dependencies:
  lint: ^1.8.2
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
